// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSqMhB8yxhefts_his9CbB0Mg_EH430vo',
    appId: '1:24054786492:web:6a142e2c7db0ef6427a3b9',
    messagingSenderId: '24054786492',
    projectId: 'asroo-shop-getx-46f01',
    authDomain: 'asroo-shop-getx-46f01.firebaseapp.com',
    storageBucket: 'asroo-shop-getx-46f01.appspot.com',
    measurementId: 'G-T0C6HJZ8BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD12Ah2c0wo6a86kKspmS4tPA_9Zx2YVM',
    appId: '1:24054786492:android:d9ad6f17e248e21e27a3b9',
    messagingSenderId: '24054786492',
    projectId: 'asroo-shop-getx-46f01',
    storageBucket: 'asroo-shop-getx-46f01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf9UA31Lg0qPcjoAHCU7uB3JkJMd-Rhr0',
    appId: '1:24054786492:ios:30ec76756db4b60827a3b9',
    messagingSenderId: '24054786492',
    projectId: 'asroo-shop-getx-46f01',
    storageBucket: 'asroo-shop-getx-46f01.appspot.com',
    androidClientId: '24054786492-h5gt5ue73g6revhb6ii99ar1lm1b00j4.apps.googleusercontent.com',
    iosClientId: '24054786492-e45jcb1fvmtpq86luqvfena9bs4ugf8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf9UA31Lg0qPcjoAHCU7uB3JkJMd-Rhr0',
    appId: '1:24054786492:ios:30ec76756db4b60827a3b9',
    messagingSenderId: '24054786492',
    projectId: 'asroo-shop-getx-46f01',
    storageBucket: 'asroo-shop-getx-46f01.appspot.com',
    androidClientId: '24054786492-h5gt5ue73g6revhb6ii99ar1lm1b00j4.apps.googleusercontent.com',
    iosClientId: '24054786492-e45jcb1fvmtpq86luqvfena9bs4ugf8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );
}
